name: Test

on:
  pull_request:

  push:
    branches:
      - develop
      - 'feature/**'

  workflow_call:
    inputs:
      test-args:
        type: string
        required: false
        description: Additional arguments for "cargo test"

  workflow_dispatch:
    inputs:
      test-args:
        type: string
        required: false
        description: Additional arguments for "cargo test"

jobs:
  call-test-workflow:
    uses: FloGa/rust-workflows/.github/workflows/test.yml@0.2.0
    with:
      test-args: ${{ inputs.test-args }}
